# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ce243a230f5f9a8cab55f1debf58a5a7d3332b3841ea869d276f2c09e2f952c814c1c525d6425d355a8ec280244220da51b8ee4328f5a75abdb2881bfbe400b

test:
  secret_key_base: e71b28ea77ea850a399980a2a82356351e16732244490de8ae1f3cb63d7f2436b8c44f2caebaa8dc83cf4435f092ff02d06aeb8547f909f334a79d133bb9778b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
